// GENERATED by `npm run build:webview` — do not edit by hand.
// Source: webview/index.html + webview/receipt-entry.ts (the web app's
// receipt.ts / postcard.ts canvas renderers, bundled).
export const RECEIPT_HTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <!-- The same three faces the receptor/postcard renderers expect. They
         await document.fonts.ready before measuring, so loading them here
         keeps the native output pixel-identical to the web. -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400..700;1,9..144,400..700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <style>
      html,
      body {
        margin: 0;
        padding: 0;
        background: transparent;
      }
    </style>
  </head>
  <body>
    <!-- \`npm run build:webview\` replaces this token with the IIFE bundle of
         receipt-entry.ts. The result is inlined into src/share/receiptHtml.ts. -->
    <script>
      "use strict";
(() => {
  // ../core/src/settle.ts
  function collectVoided(events) {
    const out = /* @__PURE__ */ new Set();
    for (const e of events) if (e.type === "void") out.add(e.targetId);
    return out;
  }
  function latestEditByTarget(events) {
    const out = /* @__PURE__ */ new Map();
    for (const e of events) {
      if (e.type !== "edit") continue;
      const prev = out.get(e.targetId);
      if (!prev || Date.parse(e.ts) >= Date.parse(prev.ts)) out.set(e.targetId, e);
    }
    return out;
  }
  function effectiveExpenses(events) {
    const voided = collectVoided(events);
    const edits = latestEditByTarget(events);
    const out = [];
    for (const e of events) {
      if (e.type !== "expense") continue;
      if (voided.has(e.id)) continue;
      const edit = edits.get(e.id);
      out.push(edit ? applyEdit(e, edit) : e);
    }
    return out;
  }
  function applyEdit(e, edit) {
    return { ...e, amount: edit.amount, ts: new Date(edit.date).toISOString() };
  }
  function realCostByMember(expenses) {
    const cost = /* @__PURE__ */ new Map();
    const add = (m, v) => {
      var _a;
      return cost.set(m, ((_a = cost.get(m)) != null ? _a : 0) + v);
    };
    for (const e of expenses) {
      if (e.split === "equal") {
        const n = e.participants.length;
        if (n === 0) continue;
        const base = Math.floor(e.amount / n);
        const remainder = e.amount - base * n;
        e.participants.forEach((p, i) => add(p, base + (i === 0 ? remainder : 0)));
      } else {
        for (const [m, owed] of Object.entries(e.split)) add(m, owed);
      }
    }
    return cost;
  }
  function formatAmount(minor, currency) {
    const zeroDecimal = /* @__PURE__ */ new Set(["JPY", "KRW", "VND", "CLP", "IDR"]);
    if (zeroDecimal.has(currency.toUpperCase())) {
      return \`\${minor.toLocaleString()} \${currency}\`;
    }
    const major = (minor / 100).toFixed(2);
    return \`\${major} \${currency}\`;
  }

  // ../src/lib/receipt.ts
  var PAPER = "#faf6ef";
  var INK = "#1a1410";
  var MUTED = "#6f6356";
  var SUBTLE = "#a89c8b";
  var ACCENT = "#c2410c";
  var POSITIVE = "#3f6212";
  var NEGATIVE = "#9f1239";
  var FONT_DISPLAY = \`'Fraunces', 'Source Serif Pro', Georgia, serif\`;
  var FONT_SANS = \`'Inter', -apple-system, BlinkMacSystemFont, system-ui, sans-serif\`;
  var FONT_MONO = \`'JetBrains Mono', 'SF Mono', ui-monospace, Menlo, monospace\`;
  var W = 540;
  var PAD_X = 36;
  var TOP_PAD = 30;
  var BOTTOM_PAD = 28;
  var TOOTH_W = 12;
  var TOOTH_H = 7;
  async function renderReceipt(input) {
    var _a;
    if (typeof document !== "undefined" && ((_a = document.fonts) == null ? void 0 : _a.ready)) {
      try {
        await document.fonts.ready;
      } catch {
      }
    }
    const measure = document.createElement("canvas").getContext("2d");
    const { blocks, titleIndex } = buildBlocks(input, measure);
    let totalH = TOP_PAD;
    for (const b of blocks) totalH += b.height;
    totalH += BOTTOM_PAD;
    const scale = Math.max(2, Math.min(3, Math.ceil(window.devicePixelRatio || 1) + 1));
    const out = document.createElement("canvas");
    out.width = Math.round(W * scale);
    out.height = Math.round(totalH * scale);
    const ctx = out.getContext("2d");
    ctx.scale(scale, scale);
    ctx.save();
    buildReceiptPath(ctx, W, totalH);
    ctx.clip();
    ctx.fillStyle = PAPER;
    ctx.fillRect(0, 0, W, totalH);
    drawPaperGrain(ctx, W, totalH, input.group.id);
    let y = TOP_PAD;
    let titleY = 0;
    for (let i = 0; i < blocks.length; i++) {
      if (i === titleIndex) titleY = y;
      blocks[i].paint(ctx, y);
      y += blocks[i].height;
    }
    if (input.group.finalizedAt && titleY > 0) {
      drawFinalizedStamp(ctx, W - PAD_X - 18, titleY + 6);
    }
    ctx.restore();
    return out;
  }
  async function renderReceiptBlob(input) {
    const canvas = await renderReceipt(input);
    return new Promise((resolve, reject) => {
      canvas.toBlob(
        (b) => b ? resolve(b) : reject(new Error("Failed to encode PNG")),
        "image/png"
      );
    });
  }
  function buildReceiptPath(ctx, w, h) {
    ctx.beginPath();
    ctx.moveTo(0, TOOTH_H);
    let x = 0;
    while (x < w) {
      const next = Math.min(x + TOOTH_W, w);
      ctx.lineTo((x + next) / 2, 0);
      ctx.lineTo(next, TOOTH_H);
      x = next;
    }
    ctx.lineTo(w, h - TOOTH_H);
    while (x > 0) {
      const next = Math.max(x - TOOTH_W, 0);
      ctx.lineTo((x + next) / 2, h);
      ctx.lineTo(next, h - TOOTH_H);
      x = next;
    }
    ctx.lineTo(0, TOOTH_H);
    ctx.closePath();
  }
  function drawPaperGrain(ctx, w, h, seed) {
    const rng = mulberry32(hashSeed("grain:" + seed));
    ctx.save();
    ctx.globalAlpha = 0.045;
    ctx.fillStyle = INK;
    const dots = Math.floor(w * h / 520);
    for (let i = 0; i < dots; i++) {
      const x = rng() * w;
      const y = rng() * h;
      const r = rng() * 0.7 + 0.18;
      ctx.fillRect(x, y, r, r);
    }
    ctx.restore();
  }
  function drawFinalizedStamp(ctx, cx, cy) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(-Math.PI / 14);
    ctx.globalAlpha = 0.78;
    ctx.strokeStyle = ACCENT;
    ctx.fillStyle = ACCENT;
    ctx.lineWidth = 1.6;
    const text = "FINALIZED";
    ctx.font = \`700 11px \${FONT_MONO}\`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    const tw = ctx.measureText(text).width;
    const padX = 8;
    const padY = 4;
    const w = tw + padX * 2;
    const h = 18;
    ctx.strokeRect(-w / 2, -h / 2, w, h);
    ctx.fillText(text, 0, 1);
    ctx.restore();
  }
  function buildBlocks(input, mctx) {
    var _a;
    const { group, balances, transfers } = input;
    const blocks = [];
    blocks.push(brandBlock());
    blocks.push(spacer(8));
    blocks.push(centeredText("\\u2014 RECEIPT \\u2014", \`500 11px \${FONT_MONO}\`, 14, MUTED));
    blocks.push(spacer(18));
    const titleIndex = blocks.length;
    blocks.push(wrappedCentered(group.name, \`600 28px \${FONT_DISPLAY}\`, 32, INK, W - PAD_X * 2, mctx));
    blocks.push(spacer(8));
    const meta = \`\${group.currency.toUpperCase()}   \\xB7   \${formatDate(/* @__PURE__ */ new Date())}   \\xB7   No. \${group.id}\`;
    blocks.push(centeredText(meta, \`500 10.5px \${FONT_MONO}\`, 12, SUBTLE));
    blocks.push(spacer(20));
    blocks.push(sectionHeader("EXPENSES"));
    blocks.push(spacer(12));
    const expenses = effectiveExpenses(group.events);
    let total = 0;
    if (expenses.length === 0) {
      blocks.push(emptyLine("\\u2014 no expenses recorded \\u2014"));
      blocks.push(spacer(8));
    } else {
      for (const e of expenses) {
        blocks.push(expenseRow(e, group.currency, mctx));
        blocks.push(spacer(10));
        total += e.amount;
      }
    }
    blocks.push(dottedDivider());
    blocks.push(spacer(8));
    blocks.push(totalRow("TOTAL", formatAmount(total, group.currency)));
    blocks.push(spacer(22));
    if (expenses.length > 0 && balances.length > 0) {
      const cost = realCostByMember(expenses);
      blocks.push(sectionHeader("REAL COST"));
      blocks.push(spacer(12));
      blocks.push(subSectionHeader("WHAT EACH ACTUALLY SPENT"));
      blocks.push(spacer(8));
      for (const b of balances) {
        blocks.push(costRow(b.member, (_a = cost.get(b.member)) != null ? _a : 0, group.currency));
      }
      blocks.push(spacer(8));
      blocks.push(captionLine(
        "Each person\\u2019s real cost once everyone settles up \\u2014 their share of every split, plus anything spent solo. Adds up to the total above.",
        mctx
      ));
      blocks.push(spacer(22));
    }
    blocks.push(sectionHeader("SETTLEMENT"));
    blocks.push(spacer(12));
    blocks.push(subSectionHeader("PER-MEMBER BALANCE"));
    blocks.push(spacer(8));
    if (balances.length === 0 || balances.every((b) => b.balance === 0)) {
      blocks.push(emptyLine("all settled up."));
    } else {
      for (const b of balances) blocks.push(balanceRow(b, group.currency));
    }
    blocks.push(spacer(18));
    if (transfers.length > 0) {
      blocks.push(subSectionHeader("SUGGESTED TRANSFERS"));
      blocks.push(spacer(8));
      for (const t of transfers) {
        blocks.push(transferRow(t, group.currency));
        blocks.push(spacer(4));
      }
    }
    blocks.push(spacer(16));
    blocks.push(dottedDivider());
    blocks.push(spacer(14));
    blocks.push(centeredItalic("Thank you for splitting stupid."));
    blocks.push(spacer(14));
    blocks.push(barcode(group.id));
    blocks.push(spacer(8));
    blocks.push(centeredText(
      \`g/\${group.id} \\xB7 \${formatDateShort(/* @__PURE__ */ new Date())}\`,
      \`500 9.5px \${FONT_MONO}\`,
      12,
      SUBTLE
    ));
    return { blocks, titleIndex };
  }
  function spacer(h) {
    return { height: h, paint: () => {
    } };
  }
  function brandBlock() {
    const SQUARE = 30;
    return {
      height: SQUARE,
      paint(ctx, y) {
        const cx = W / 2;
        ctx.font = \`600 17px \${FONT_DISPLAY}\`;
        const word = "SplitStupid";
        const wordW = ctx.measureText(word).width;
        const gap = 10;
        const groupW = SQUARE + gap + wordW;
        const x0 = cx - groupW / 2;
        ctx.fillStyle = INK;
        roundRect(ctx, x0, y, SQUARE, SQUARE, 6);
        ctx.fill();
        ctx.fillStyle = PAPER;
        ctx.font = \`italic 700 21px \${FONT_DISPLAY}\`;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText("S", x0 + SQUARE / 2, y + SQUARE / 2 + 1);
        ctx.fillStyle = INK;
        ctx.font = \`600 18px \${FONT_DISPLAY}\`;
        ctx.textAlign = "left";
        ctx.textBaseline = "middle";
        ctx.fillText(word, x0 + SQUARE + gap, y + SQUARE / 2);
      }
    };
  }
  function centeredText(text, font, lineH, color) {
    return {
      height: lineH,
      paint(ctx, y) {
        ctx.font = font;
        ctx.fillStyle = color;
        ctx.textAlign = "center";
        ctx.textBaseline = "top";
        ctx.fillText(text, W / 2, y);
      }
    };
  }
  function centeredItalic(text) {
    return {
      height: 18,
      paint(ctx, y) {
        ctx.font = \`italic 600 14px \${FONT_DISPLAY}\`;
        ctx.fillStyle = MUTED;
        ctx.textAlign = "center";
        ctx.textBaseline = "top";
        ctx.fillText(text, W / 2, y);
      }
    };
  }
  function wrappedCentered(text, font, lineH, color, maxW, mctx) {
    mctx.font = font;
    const lines = wrapText(mctx, text, maxW);
    return {
      height: lines.length * lineH,
      paint(ctx, y) {
        ctx.font = font;
        ctx.fillStyle = color;
        ctx.textAlign = "center";
        ctx.textBaseline = "top";
        lines.forEach((ln, i) => ctx.fillText(ln, W / 2, y + i * lineH));
      }
    };
  }
  function sectionHeader(label) {
    const HEIGHT = 16;
    return {
      height: HEIGHT,
      paint(ctx, y) {
        const cy = y + HEIGHT / 2;
        ctx.font = \`600 10.5px \${FONT_MONO}\`;
        ctx.fillStyle = INK;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        const labelW = ctx.measureText(label).width;
        const labelGap = 14;
        ctx.strokeStyle = INK;
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(PAD_X, cy);
        ctx.lineTo(W / 2 - labelW / 2 - labelGap, cy);
        ctx.moveTo(W / 2 + labelW / 2 + labelGap, cy);
        ctx.lineTo(W - PAD_X, cy);
        ctx.stroke();
        ctx.fillText(label, W / 2, cy);
      }
    };
  }
  function subSectionHeader(label) {
    return {
      height: 14,
      paint(ctx, y) {
        ctx.font = \`600 9.5px \${FONT_MONO}\`;
        ctx.fillStyle = MUTED;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(label, PAD_X, y);
      }
    };
  }
  function expenseRow(e, currency, mctx) {
    const innerW = W - PAD_X * 2;
    const titleFont = \`500 13px \${FONT_SANS}\`;
    const amountFont = \`600 13px \${FONT_MONO}\`;
    const noteFont = \`italic 500 12px \${FONT_DISPLAY}\`;
    const splitFont = \`500 10px \${FONT_MONO}\`;
    const splitText = \`split among \${e.participants.join(", ")}\`;
    const dateText = formatDateShort(new Date(e.ts));
    mctx.font = noteFont;
    const noteLines = e.note ? wrapText(mctx, \`\\u201C\${e.note}\\u201D\`, innerW) : [];
    mctx.font = splitFont;
    const splitMaxW = innerW - mctx.measureText(dateText).width - 12;
    const splitLines = wrapText(mctx, splitText, splitMaxW);
    const titleH = 18;
    const noteH = noteLines.length * 16;
    const splitH = Math.max(splitLines.length, 1) * 14;
    const HEIGHT = titleH + (noteH ? noteH + 2 : 0) + splitH + 2;
    return {
      height: HEIGHT,
      paint(ctx, y) {
        ctx.font = titleFont;
        ctx.fillStyle = INK;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(\`\${e.payer} paid\`, PAD_X, y);
        ctx.font = amountFont;
        ctx.textAlign = "right";
        ctx.fillText(formatAmount(e.amount, currency), W - PAD_X, y);
        let cy = y + titleH;
        if (noteLines.length) {
          ctx.font = noteFont;
          ctx.fillStyle = MUTED;
          ctx.textAlign = "left";
          for (const ln of noteLines) {
            ctx.fillText(ln, PAD_X, cy);
            cy += 16;
          }
          cy += 2;
        }
        ctx.font = splitFont;
        ctx.fillStyle = SUBTLE;
        ctx.textAlign = "left";
        splitLines.forEach((ln, i) => ctx.fillText(ln, PAD_X, cy + i * 14));
        ctx.textAlign = "right";
        ctx.fillText(dateText, W - PAD_X, cy);
      }
    };
  }
  function totalRow(label, value) {
    return {
      height: 22,
      paint(ctx, y) {
        ctx.font = \`600 10.5px \${FONT_MONO}\`;
        ctx.fillStyle = MUTED;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(label, PAD_X, y + 5);
        ctx.font = \`700 16px \${FONT_MONO}\`;
        ctx.fillStyle = INK;
        ctx.textAlign = "right";
        ctx.fillText(value, W - PAD_X, y);
      }
    };
  }
  function balanceRow(b, currency) {
    return {
      height: 19,
      paint(ctx, y) {
        ctx.font = \`500 13px \${FONT_SANS}\`;
        ctx.fillStyle = INK;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(b.member, PAD_X, y + 1);
        const sign = b.balance > 0 ? "+" : "";
        const color = b.balance > 0 ? POSITIVE : b.balance < 0 ? NEGATIVE : SUBTLE;
        ctx.font = \`600 12.5px \${FONT_MONO}\`;
        ctx.fillStyle = color;
        ctx.textAlign = "right";
        ctx.fillText(\`\${sign}\${formatAmount(b.balance, currency)}\`, W - PAD_X, y + 1);
      }
    };
  }
  function costRow(member, cost, currency) {
    return {
      height: 19,
      paint(ctx, y) {
        ctx.font = \`500 13px \${FONT_SANS}\`;
        ctx.fillStyle = INK;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(member, PAD_X, y + 1);
        ctx.font = \`600 12.5px \${FONT_MONO}\`;
        ctx.fillStyle = cost > 0 ? INK : SUBTLE;
        ctx.textAlign = "right";
        ctx.fillText(formatAmount(cost, currency), W - PAD_X, y + 1);
      }
    };
  }
  function captionLine(text, mctx) {
    const font = \`italic 500 11px \${FONT_DISPLAY}\`;
    const lineH = 15;
    const maxW = W - PAD_X * 2;
    mctx.font = font;
    const lines = wrapText(mctx, text, maxW);
    return {
      height: lines.length * lineH,
      paint(ctx, y) {
        ctx.font = font;
        ctx.fillStyle = MUTED;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        lines.forEach((ln, i) => ctx.fillText(ln, PAD_X, y + i * lineH));
      }
    };
  }
  function transferRow(t, currency) {
    return {
      height: 22,
      paint(ctx, y) {
        ctx.fillStyle = ACCENT;
        ctx.beginPath();
        ctx.arc(PAD_X + 3, y + 9, 3, 0, Math.PI * 2);
        ctx.fill();
        ctx.font = \`500 13px \${FONT_SANS}\`;
        ctx.fillStyle = INK;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(\`\${t.from}  \\u2192  \${t.to}\`, PAD_X + 14, y + 2);
        ctx.font = \`700 13px \${FONT_MONO}\`;
        ctx.fillStyle = ACCENT;
        ctx.textAlign = "right";
        ctx.fillText(formatAmount(t.amount, currency), W - PAD_X, y + 2);
      }
    };
  }
  function emptyLine(text) {
    return {
      height: 18,
      paint(ctx, y) {
        ctx.font = \`italic 500 12px \${FONT_DISPLAY}\`;
        ctx.fillStyle = SUBTLE;
        ctx.textAlign = "center";
        ctx.textBaseline = "top";
        ctx.fillText(text, W / 2, y);
      }
    };
  }
  function dottedDivider() {
    const HEIGHT = 6;
    return {
      height: HEIGHT,
      paint(ctx, y) {
        ctx.fillStyle = SUBTLE;
        const step = 4;
        const r = 0.85;
        for (let x = PAD_X; x <= W - PAD_X; x += step) {
          ctx.beginPath();
          ctx.arc(x, y + HEIGHT / 2, r, 0, Math.PI * 2);
          ctx.fill();
        }
      }
    };
  }
  function barcode(seed) {
    const HEIGHT = 30;
    return {
      height: HEIGHT,
      paint(ctx, y) {
        const rng = mulberry32(hashSeed("bar:" + seed));
        const x0 = PAD_X;
        const x1 = W - PAD_X;
        let x = x0;
        ctx.fillStyle = INK;
        while (x < x1) {
          const w = rng() < 0.5 ? 1 : rng() < 0.45 ? 3 : 2;
          const gap = rng() < 0.7 ? 1.6 : 3;
          if (rng() < 0.86) ctx.fillRect(x, y, w, HEIGHT);
          x += w + gap;
        }
      }
    };
  }
  function wrapText(ctx, text, maxW) {
    const tokens = text.split(/(\\s+)/);
    const lines = [];
    let cur = "";
    for (const tok of tokens) {
      const trial = cur + tok;
      if (ctx.measureText(trial).width <= maxW) {
        cur = trial;
        continue;
      }
      if (cur.trim()) lines.push(cur.trimEnd());
      if (ctx.measureText(tok).width > maxW) {
        let buf = "";
        for (const ch of tok) {
          if (ctx.measureText(buf + ch).width > maxW) {
            if (buf) lines.push(buf);
            buf = ch;
          } else {
            buf += ch;
          }
        }
        cur = buf;
      } else {
        cur = tok.trimStart();
      }
    }
    if (cur.trim()) lines.push(cur.trimEnd());
    return lines.length ? lines : [""];
  }
  function roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }
  function mulberry32(a) {
    return function() {
      let t = a += 1831565813;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  function hashSeed(s) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }
  function formatDate(d) {
    const y = d.getFullYear();
    const mo = String(d.getMonth() + 1).padStart(2, "0");
    const da = String(d.getDate()).padStart(2, "0");
    const hh = String(d.getHours()).padStart(2, "0");
    const mm = String(d.getMinutes()).padStart(2, "0");
    return \`\${y}-\${mo}-\${da} \${hh}:\${mm}\`;
  }
  function formatDateShort(d) {
    const y = d.getFullYear();
    const mo = String(d.getMonth() + 1).padStart(2, "0");
    const da = String(d.getDate()).padStart(2, "0");
    return \`\${y}-\${mo}-\${da}\`;
  }

  // ../src/lib/postcard.ts
  var PAPER2 = "#faf6ef";
  var INK2 = "#1a1410";
  var MUTED2 = "#6f6356";
  var ACCENT2 = "#c2410c";
  var POSITIVE2 = "#3f6212";
  var FONT_DISPLAY2 = \`'Fraunces', 'Source Serif Pro', Georgia, serif\`;
  var FONT_MONO2 = \`'JetBrains Mono', 'SF Mono', ui-monospace, Menlo, monospace\`;
  var W2 = 720;
  var H = 460;
  var PAD = 38;
  async function renderPostcard(input) {
    var _a, _b;
    if (typeof document !== "undefined" && ((_a = document.fonts) == null ? void 0 : _a.ready)) {
      try {
        await document.fonts.ready;
      } catch {
      }
    }
    const { group } = input;
    const displayMembers = group.members.slice(0, 4);
    const remaining = Math.max(0, group.members.length - displayMembers.length);
    const avatars = await Promise.all(displayMembers.map(loadAvatar));
    const scale = Math.max(2, Math.min(3, Math.ceil(window.devicePixelRatio || 1) + 1));
    const out = document.createElement("canvas");
    out.width = Math.round(W2 * scale);
    out.height = Math.round(H * scale);
    const ctx = out.getContext("2d");
    ctx.scale(scale, scale);
    ctx.fillStyle = PAPER2;
    ctx.fillRect(0, 0, W2, H);
    drawPaperGrain2(ctx, W2, H, group.id);
    ctx.save();
    ctx.globalAlpha = 0.22;
    ctx.strokeStyle = INK2;
    ctx.lineWidth = 1;
    ctx.setLineDash([2, 4]);
    ctx.strokeRect(14, 14, W2 - 28, H - 28);
    ctx.restore();
    drawBrand(ctx, PAD, 32);
    drawTitle(ctx, group.name, PAD, 116, 380);
    ctx.font = \`500 11px \${FONT_MONO2}\`;
    ctx.fillStyle = MUTED2;
    ctx.textBaseline = "top";
    drawTrackedText(
      ctx,
      buildSubtitle(group),
      PAD + 2,
      188,
      11 * 0.22,
      "left"
    );
    drawAvatars(ctx, displayMembers, avatars, remaining, PAD, 232);
    drawPostmark(ctx, W2 - 134, 130, (_b = group.finalizedAt) != null ? _b : group.createdAt);
    drawTotal(ctx, group);
    ctx.font = \`italic 600 17px \${FONT_DISPLAY2}\`;
    ctx.fillStyle = MUTED2;
    ctx.textAlign = "left";
    ctx.textBaseline = "alphabetic";
    ctx.fillText("Wish you were splitting here.", PAD, H - 38);
    drawFinalizedStamp2(ctx, PAD + 50, H - 78);
    return out;
  }
  async function renderPostcardBlob(input) {
    const canvas = await renderPostcard(input);
    return new Promise((resolve, reject) => {
      canvas.toBlob(
        (b) => b ? resolve(b) : reject(new Error("Failed to encode PNG")),
        "image/png"
      );
    });
  }
  function drawBrand(ctx, x, y) {
    const s = 32;
    ctx.fillStyle = INK2;
    roundRect2(ctx, x, y, s, s, 6);
    ctx.fill();
    ctx.fillStyle = PAPER2;
    ctx.font = \`italic 700 22px \${FONT_DISPLAY2}\`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText("S", x + s / 2, y + s / 2 + 1);
    ctx.fillStyle = INK2;
    ctx.font = \`600 17px \${FONT_DISPLAY2}\`;
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    ctx.fillText("SplitStupid", x + s + 12, y + 2);
    ctx.fillStyle = MUTED2;
    ctx.font = \`500 9px \${FONT_MONO2}\`;
    drawTrackedText(ctx, "\\u2014 TRIP POSTCARD \\u2014", x + s + 12, y + 22, 9 * 0.22, "left");
  }
  function drawTitle(ctx, title, x, y, maxW) {
    let size = 60;
    while (size > 28) {
      ctx.font = \`600 \${size}px \${FONT_DISPLAY2}\`;
      if (ctx.measureText(title).width <= maxW) break;
      size -= 4;
    }
    ctx.fillStyle = INK2;
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    ctx.fillText(title, x, y);
  }
  function buildSubtitle(group) {
    var _a;
    const start = group.createdAt;
    const end = (_a = group.finalizedAt) != null ? _a : Date.now();
    const range = formatDateRange(start, end);
    const n = group.members.length;
    return \`\${range}   \\xB7   \${n} \${n === 1 ? "SPLITTER" : "SPLITTERS"}\`;
  }
  function formatDateRange(startMs, endMs) {
    const months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
    const s = new Date(startMs);
    const e = new Date(endMs);
    if (s.getFullYear() !== e.getFullYear()) {
      return \`\${months[s.getMonth()]} \${s.getDate()}, \${s.getFullYear()} \\u2014 \${months[e.getMonth()]} \${e.getDate()}, \${e.getFullYear()}\`;
    }
    if (s.getMonth() !== e.getMonth()) {
      return \`\${months[s.getMonth()]} \${s.getDate()} \\u2014 \${months[e.getMonth()]} \${e.getDate()}, \${s.getFullYear()}\`;
    }
    if (s.getDate() === e.getDate()) {
      return \`\${months[s.getMonth()]} \${s.getDate()}, \${s.getFullYear()}\`;
    }
    return \`\${months[s.getMonth()]} \${s.getDate()} \\u2014 \${e.getDate()}, \${s.getFullYear()}\`;
  }
  function drawAvatars(ctx, members, avatars, remaining, x, y) {
    const r = 19;
    const gap = 12;
    const startX = x + r;
    members.forEach((login, i) => {
      drawAvatarCircle(ctx, startX + i * (r * 2 + gap), y + r, r, avatars[i], login);
    });
    const lastEnd = members.length === 0 ? x : startX + (members.length - 1) * (r * 2 + gap) + r;
    let cx = lastEnd + 14;
    if (remaining > 0) {
      ctx.font = \`500 11px \${FONT_MONO2}\`;
      ctx.fillStyle = MUTED2;
      ctx.textAlign = "left";
      ctx.textBaseline = "middle";
      const tail = \`+\${remaining} more\`;
      ctx.fillText(tail, cx, y + r);
      cx += ctx.measureText(tail).width + 14;
    }
    ctx.font = \`italic 500 16px \${FONT_DISPLAY2}\`;
    ctx.fillStyle = MUTED2;
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";
    const maxW = W2 - 220 - cx;
    let roster = members.join(" \\xB7 ");
    if (ctx.measureText(roster).width > maxW) {
      while (roster.length > 4 && ctx.measureText(roster + "\\u2026").width > maxW) {
        roster = roster.slice(0, -1);
      }
      roster = roster + "\\u2026";
    }
    if (roster.length > 0) ctx.fillText(roster, cx, y + r);
  }
  function drawAvatarCircle(ctx, cx, cy, r, img, login) {
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.clip();
    if (img && img.naturalWidth > 0) {
      ctx.drawImage(img, cx - r, cy - r, r * 2, r * 2);
    } else {
      const [c1, c2] = colorPairForLogin(login);
      const grad = ctx.createLinearGradient(cx - r, cy - r, cx + r, cy + r);
      grad.addColorStop(0, c1);
      grad.addColorStop(1, c2);
      ctx.fillStyle = grad;
      ctx.fillRect(cx - r, cy - r, r * 2, r * 2);
      ctx.fillStyle = "#fff8f1";
      ctx.font = \`italic 700 \${Math.round(r * 0.95)}px \${FONT_DISPLAY2}\`;
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText((login[0] || "?").toUpperCase(), cx, cy + 1);
    }
    ctx.restore();
    ctx.save();
    ctx.strokeStyle = "rgba(26, 20, 16, 0.18)";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.stroke();
    ctx.restore();
  }
  var COLOR_PAIRS = [
    ["#f1c597", "#c2410c"],
    ["#d6c5a0", "#6f6356"],
    ["#e8b3b3", "#9f1239"],
    ["#b8d49a", "#3f6212"],
    ["#cab5e0", "#6b46c1"]
  ];
  function colorPairForLogin(login) {
    let h = 0;
    for (let i = 0; i < login.length; i++) h = h * 31 + login.charCodeAt(i) >>> 0;
    return COLOR_PAIRS[h % COLOR_PAIRS.length];
  }
  function drawPostmark(ctx, cx, cy, finalizedMs) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(Math.PI / 22);
    ctx.strokeStyle = ACCENT2;
    ctx.fillStyle = ACCENT2;
    ctx.lineWidth = 2.5;
    ctx.setLineDash([4, 3]);
    ctx.beginPath();
    ctx.arc(0, 0, 80, 0, Math.PI * 2);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.lineWidth = 1.2;
    ctx.beginPath();
    ctx.arc(0, 0, 65, 0, Math.PI * 2);
    ctx.stroke();
    ctx.save();
    ctx.globalAlpha = 0.5;
    ctx.lineWidth = 0.6;
    ctx.beginPath();
    ctx.arc(0, 0, 56, 0, Math.PI * 2);
    ctx.stroke();
    ctx.restore();
    ctx.font = \`700 10px \${FONT_MONO2}\`;
    ctx.textBaseline = "middle";
    drawTrackedText(ctx, "\\u2605 SETTLED \\u2605", 0, -36, 10 * 0.32, "center");
    ctx.font = \`italic 700 32px \${FONT_DISPLAY2}\`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText("spent", 0, 2);
    const months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
    const d = new Date(finalizedMs);
    const stampDate = \`\${months[d.getMonth()]} \\xB7 \${toRoman(d.getFullYear())}\`;
    ctx.font = \`500 9px \${FONT_MONO2}\`;
    drawTrackedText(ctx, stampDate, 0, 36, 9 * 0.28, "center");
    ctx.restore();
  }
  function drawTotal(ctx, group) {
    const { total, count } = computeTotal(group);
    const n = Math.max(group.members.length, 1);
    const perPerson = Math.floor(total / n);
    const x = W2 - PAD;
    let y = H - 102;
    ctx.fillStyle = MUTED2;
    ctx.font = \`500 9px \${FONT_MONO2}\`;
    ctx.textBaseline = "top";
    drawTrackedText(ctx, "GRAND TOTAL", x, y, 9 * 0.28, "right");
    y += 14;
    ctx.font = \`600 44px \${FONT_DISPLAY2}\`;
    ctx.fillStyle = INK2;
    ctx.textAlign = "right";
    ctx.fillText(formatAmount(total, group.currency), x, y);
    y += 50;
    ctx.font = \`500 10px \${FONT_MONO2}\`;
    ctx.fillStyle = MUTED2;
    ctx.fillText(
      \`\${formatAmount(perPerson, group.currency)} per splitter \\xB7 \${count} \${count === 1 ? "expense" : "expenses"}\`,
      x,
      y
    );
  }
  function computeTotal(group) {
    const voided = /* @__PURE__ */ new Set();
    for (const e of group.events) if (e.type === "void") voided.add(e.targetId);
    let total = 0;
    let count = 0;
    for (const e of group.events) {
      if (e.type === "expense" && !voided.has(e.id)) {
        total += e.amount;
        count += 1;
      }
    }
    return { total, count };
  }
  function drawFinalizedStamp2(ctx, cx, cy) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(-Math.PI / 30);
    ctx.strokeStyle = POSITIVE2;
    ctx.fillStyle = POSITIVE2;
    ctx.lineWidth = 1.5;
    ctx.font = \`700 11px \${FONT_MONO2}\`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    const text = "FINALIZED";
    const tw = ctx.measureText(text).width;
    const w = tw + 22;
    const h = 22;
    ctx.save();
    ctx.fillStyle = "rgba(255, 255, 255, 0.45)";
    ctx.fillRect(-w / 2, -h / 2, w, h);
    ctx.restore();
    ctx.strokeRect(-w / 2, -h / 2, w, h);
    ctx.fillText(text, 0, 1);
    ctx.restore();
  }
  async function loadAvatar(login) {
    return new Promise((resolve) => {
      const img = new Image();
      let settled = false;
      const finish = (val) => {
        if (settled) return;
        settled = true;
        resolve(val);
      };
      img.crossOrigin = "anonymous";
      img.onload = () => finish(img);
      img.onerror = () => finish(null);
      img.src = \`https://github.com/\${encodeURIComponent(login)}.png?size=120\`;
      setTimeout(() => finish(null), 4e3);
    });
  }
  function drawPaperGrain2(ctx, w, h, seed) {
    const rng = mulberry322(hashSeed2("postcard:" + seed));
    ctx.save();
    ctx.globalAlpha = 0.045;
    ctx.fillStyle = INK2;
    const dots = Math.floor(w * h / 520);
    for (let i = 0; i < dots; i++) {
      const x = rng() * w;
      const y = rng() * h;
      const r = rng() * 0.7 + 0.18;
      ctx.fillRect(x, y, r, r);
    }
    ctx.restore();
  }
  function drawTrackedText(ctx, text, x, y, letterPx, align = "left") {
    const baseAlign = ctx.textAlign;
    ctx.textAlign = "left";
    let total = 0;
    for (let i = 0; i < text.length; i++) {
      total += ctx.measureText(text[i]).width;
      if (i < text.length - 1) total += letterPx;
    }
    let cx = x;
    if (align === "center") cx = x - total / 2;
    else if (align === "right") cx = x - total;
    for (const ch of text) {
      ctx.fillText(ch, cx, y);
      cx += ctx.measureText(ch).width + letterPx;
    }
    ctx.textAlign = baseAlign;
  }
  function roundRect2(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }
  function mulberry322(a) {
    return function() {
      let t = a += 1831565813;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  function hashSeed2(s) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }
  function toRoman(n) {
    const pairs = [
      [1e3, "M"],
      [900, "CM"],
      [500, "D"],
      [400, "CD"],
      [100, "C"],
      [90, "XC"],
      [50, "L"],
      [40, "XL"],
      [10, "X"],
      [9, "IX"],
      [5, "V"],
      [4, "IV"],
      [1, "I"]
    ];
    let out = "";
    let r = n;
    for (const [v, sym] of pairs) {
      while (r >= v) {
        out += sym;
        r -= v;
      }
    }
    return out;
  }

  // webview/receipt-entry.ts
  function post(obj) {
    var _a;
    (_a = window.ReactNativeWebView) == null ? void 0 : _a.postMessage(JSON.stringify(obj));
  }
  function blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result);
      r.onerror = () => reject(new Error("failed to read blob"));
      r.readAsDataURL(blob);
    });
  }
  async function handle(msg) {
    var _a;
    try {
      const blob = msg.kind === "postcard" ? await renderPostcardBlob({ group: msg.group }) : await renderReceiptBlob({ group: msg.group, balances: msg.balances, transfers: msg.transfers });
      post({ type: "png", dataUrl: await blobToDataUrl(blob) });
    } catch (e) {
      post({ type: "error", message: (_a = e == null ? void 0 : e.message) != null ? _a : "render failed" });
    }
  }
  function onMessage(raw) {
    if (typeof raw !== "string") return;
    let msg;
    try {
      msg = JSON.parse(raw);
    } catch {
      return;
    }
    if (msg && (msg.kind === "receipt" || msg.kind === "postcard")) void handle(msg);
  }
  window.addEventListener("message", (e) => onMessage(e.data));
  document.addEventListener("message", (e) => onMessage(e.data));
  post({ type: "ready" });
})();

    </script>
  </body>
</html>
`
