// Second half of `npm run build:webview`. esbuild has already produced
// assets/receipt-bundle.js (the IIFE of webview/receipt-entry.ts); here we
// splice it into webview/index.html and emit src/share/receiptHtml.ts, a
// plain TS module exporting the finished document as a string. Loading the
// WebView from an inline string (vs a file:// asset) sidesteps the iOS /
// Android asset-path differences and Metro asset config entirely.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const template = readFileSync(join(root, 'webview/index.html'), 'utf8')
const bundle = readFileSync(join(root, 'assets/receipt-bundle.js'), 'utf8')

const html = template.replace('/*__BUNDLE__*/', () => bundle)

// Escape for a TS template literal.
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

const out = `// GENERATED by \`npm run build:webview\` — do not edit by hand.
// Source: webview/index.html + webview/receipt-entry.ts (the web app's
// receipt.ts / postcard.ts canvas renderers, bundled).
export const RECEIPT_HTML = \`${escaped}\`
`

writeFileSync(join(root, 'src/share/receiptHtml.ts'), out)
console.log('wrote src/share/receiptHtml.ts (%d KB)', Math.round(out.length / 1024))
